const EXCEL_TO_ANAPLAN = [
  // ── Math & Trig ──
  { excel: "ABS", anaplan: "ABS", type: "direct", category: "Math & Trig", notes: "Direct equivalent. Returns the absolute value of a number." },
  { excel: "CEILING", anaplan: "MROUND", type: "alternative", category: "Math & Trig", notes: "Use MROUND(Value, Multiple, 1) with rounding direction = 1 (up) to replicate CEILING behavior." },
  { excel: "EXP", anaplan: "EXP", type: "direct", category: "Math & Trig", notes: "Direct equivalent. Raises e to the specified power." },
  { excel: "FLOOR", anaplan: "MROUND", type: "alternative", category: "Math & Trig", notes: "Use MROUND(Value, Multiple, -1) with rounding direction = -1 (down) to replicate FLOOR behavior." },
  { excel: "INT", anaplan: "ROUND", type: "alternative", category: "Math & Trig", notes: "Use ROUND(Value, 0, -1) to round down to the nearest integer." },
  { excel: "LN", anaplan: "LN", type: "direct", category: "Math & Trig", notes: "Direct equivalent. Returns the natural logarithm of a number." },
  { excel: "LOG", anaplan: "LOG", type: "direct", category: "Math & Trig", notes: "Direct equivalent. Returns the logarithm of a number to the specified base." },
  { excel: "LOG10", anaplan: "LOG", type: "alternative", category: "Math & Trig", notes: "Use LOG(Number, 10) to get the base-10 logarithm." },
  { excel: "MOD", anaplan: "MOD", type: "direct", category: "Math & Trig", notes: "Direct equivalent. Returns the remainder after division." },
  { excel: "MROUND", anaplan: "MROUND", type: "direct", category: "Math & Trig", notes: "Direct equivalent. Rounds a number to the nearest multiple." },
  { excel: "POWER", anaplan: "POWER", type: "direct", category: "Math & Trig", notes: "Direct equivalent. Raises a number to a power." },
  { excel: "ROUND", anaplan: "ROUND", type: "direct", category: "Math & Trig", notes: "Direct equivalent. Rounds a number to a specified number of digits." },
  { excel: "ROUNDDOWN", anaplan: "ROUND", type: "alternative", category: "Math & Trig", notes: "Use ROUND(Value, Decimals, -1) with rounding direction = -1 to always round toward zero." },
  { excel: "ROUNDUP", anaplan: "ROUND", type: "alternative", category: "Math & Trig", notes: "Use ROUND(Value, Decimals, 1) with rounding direction = 1 to always round away from zero." },
  { excel: "SIGN", anaplan: "SIGN", type: "direct", category: "Math & Trig", notes: "Direct equivalent. Returns 1, 0, or -1 based on the sign of a number." },
  { excel: "SQRT", anaplan: "SQRT", type: "direct", category: "Math & Trig", notes: "Direct equivalent. Returns the square root of a number." },
  { excel: "SUM", anaplan: "SUM", type: "alternative", category: "Math & Trig", notes: "Anaplan SUM is an aggregation function that sums across list dimensions using mappings, not a range of cells. For adding values: use the + operator." },
  { excel: "SUMIF", anaplan: "SUM + mapping", type: "alternative", category: "Math & Trig", notes: "Use SUM with a mapping table. When your mapping table maps Source list items to Target list items, SUM automatically aggregates matching items." },
  { excel: "SUMPRODUCT", anaplan: "SUM + multiplication", type: "alternative", category: "Math & Trig", notes: "Multiply the line items together in a detail module, then use SUM aggregation to total the products." },

  // ── Logical ──
  { excel: "IF", anaplan: "IF THEN ELSE", type: "alternative", category: "Logical", notes: "Anaplan syntax: IF condition THEN value1 ELSE value2. Nesting is supported for multiple conditions." },
  { excel: "IFERROR", anaplan: "IF + guard", type: "alternative", category: "Logical", notes: "No direct equivalent. Use guard patterns like IF denominator <> 0 THEN ... ELSE 0 to prevent errors proactively." },
  { excel: "AND", anaplan: "AND operator", type: "alternative", category: "Logical", notes: "Use the AND operator between conditions: IF condition1 AND condition2 THEN ... ELSE ..." },
  { excel: "OR", anaplan: "OR operator", type: "alternative", category: "Logical", notes: "Use the OR operator between conditions: IF condition1 OR condition2 THEN ... ELSE ..." },
  { excel: "NOT", anaplan: "NOT operator", type: "alternative", category: "Logical", notes: "Use the NOT operator: NOT(Boolean expression). Returns the opposite Boolean value." },
  { excel: "TRUE", anaplan: "TRUE", type: "direct", category: "Logical", notes: "Use the Boolean constant TRUE directly." },
  { excel: "FALSE", anaplan: "FALSE", type: "direct", category: "Logical", notes: "Use the Boolean constant FALSE directly." },

  // ── Text ──
  { excel: "CONCATENATE", anaplan: "& operator", type: "alternative", category: "Text", notes: "Use the ampersand (&) operator to join text strings: Text1 & \" \" & Text2." },
  { excel: "CONCAT", anaplan: "& operator", type: "alternative", category: "Text", notes: "Same as CONCATENATE. Use the & operator to join strings." },
  { excel: "FIND", anaplan: "FIND", type: "direct", category: "Text", notes: "Direct equivalent. Returns the position of a substring within text. Returns 0 (not an error) if not found." },
  { excel: "LEFT", anaplan: "LEFT", type: "direct", category: "Text", notes: "Direct equivalent. Extracts characters from the start of a text string." },
  { excel: "LEN", anaplan: "LENGTH", type: "alternative", category: "Text", notes: "Anaplan uses LENGTH() instead of LEN(). Same functionality—returns the number of characters." },
  { excel: "LOWER", anaplan: "LOWER", type: "direct", category: "Text", notes: "Direct equivalent. Converts text to lowercase." },
  { excel: "MID", anaplan: "MID", type: "direct", category: "Text", notes: "Direct equivalent. Extracts characters from the middle of a text string." },
  { excel: "PROPER", anaplan: "No equivalent", type: "none", category: "Text", notes: "No direct equivalent. Workaround: use UPPER(LEFT(Text, 1)) & LOWER(MID(Text, 2)) for simple cases." },
  { excel: "REPLACE", anaplan: "SUBSTITUTE", type: "alternative", category: "Text", notes: "SUBSTITUTE replaces all occurrences of a search string. For positional replacement, combine LEFT, MID, and RIGHT." },
  { excel: "RIGHT", anaplan: "RIGHT", type: "direct", category: "Text", notes: "Direct equivalent. Extracts characters from the end of a text string." },
  { excel: "SEARCH", anaplan: "FIND", type: "alternative", category: "Text", notes: "Anaplan's FIND is case-sensitive. There is no case-insensitive search; use FIND(LOWER(search), LOWER(text)) as a workaround." },
  { excel: "SUBSTITUTE", anaplan: "SUBSTITUTE", type: "direct", category: "Text", notes: "Direct equivalent. Replaces occurrences of old text with new text." },
  { excel: "TEXT", anaplan: "TEXT", type: "direct", category: "Text", notes: "Converts a number to text. Anaplan's TEXT does not support format strings like Excel's TEXT(value, \"$#,##0\")." },
  { excel: "TRIM", anaplan: "TRIM", type: "direct", category: "Text", notes: "Direct equivalent. Removes leading, trailing, and extra spaces." },
  { excel: "UPPER", anaplan: "UPPER", type: "direct", category: "Text", notes: "Direct equivalent. Converts text to uppercase." },
  { excel: "VALUE", anaplan: "VALUE", type: "direct", category: "Text", notes: "Direct equivalent. Converts a text representation of a number to a number." },

  // ── Lookup & Reference ──
  { excel: "VLOOKUP", anaplan: "LOOKUP", type: "alternative", category: "Lookup & Reference", notes: "Use Source[LOOKUP: Mapping]. Anaplan uses list-based mappings instead of column ranges. The mapping line item links source to target." },
  { excel: "HLOOKUP", anaplan: "LOOKUP", type: "alternative", category: "Lookup & Reference", notes: "Same as VLOOKUP equivalent. Anaplan LOOKUP works across modules using list mappings—no row/column distinction." },
  { excel: "INDEX", anaplan: "LOOKUP / SELECT", type: "alternative", category: "Lookup & Reference", notes: "Use LOOKUP for mapping-based retrieval or SELECT to pick a specific list item or time period." },
  { excel: "MATCH", anaplan: "FINDITEM", type: "alternative", category: "Lookup & Reference", notes: "FINDITEM(List, Text) searches a list for a matching item. Returns the list item (not a row number)." },
  { excel: "INDEX/MATCH", anaplan: "LOOKUP", type: "alternative", category: "Lookup & Reference", notes: "The common INDEX/MATCH pattern is replaced by Source[LOOKUP: Mapping] in Anaplan. Define a mapping line item that links source to target." },
  { excel: "OFFSET", anaplan: "OFFSET", type: "alternative", category: "Lookup & Reference", notes: "Anaplan's OFFSET shifts along time or list dimensions (not cell ranges). Syntax: OFFSET(Value, Periods, Substitute)." },
  { excel: "CHOOSE", anaplan: "SELECT / FINDITEM", type: "alternative", category: "Lookup & Reference", notes: "Use SELECT to pick a specific item, or FINDITEM to match text to a list item, then LOOKUP." },
  { excel: "HYPERLINK", anaplan: "MAKELINK", type: "alternative", category: "Lookup & Reference", notes: "MAKELINK(Display text, URL) creates a clickable hyperlink in Anaplan." },
  { excel: "ADDRESS", anaplan: "NAME", type: "alternative", category: "Lookup & Reference", notes: "NAME() returns the display name of a list item as text." },

  // ── Date & Time ──
  { excel: "DATE", anaplan: "DATE", type: "direct", category: "Date & Time", notes: "Direct equivalent. Creates a date from year, month, and day values." },
  { excel: "DAY", anaplan: "DAY", type: "direct", category: "Date & Time", notes: "Direct equivalent. Returns the day of the month from a date." },
  { excel: "MONTH", anaplan: "MONTH", type: "direct", category: "Date & Time", notes: "Direct equivalent. Returns the month number from a date." },
  { excel: "YEAR", anaplan: "YEAR", type: "direct", category: "Date & Time", notes: "Direct equivalent. Returns the year from a date." },
  { excel: "TODAY", anaplan: "CURRENTPERIODSTART", type: "alternative", category: "Date & Time", notes: "No exact TODAY() equivalent. CURRENTPERIODSTART() and CURRENTPERIODEND() return the current period's date boundaries." },
  { excel: "EDATE", anaplan: "ADDMONTHS", type: "alternative", category: "Date & Time", notes: "ADDMONTHS(Date, N) adds N months to a date. Equivalent to EDATE." },
  { excel: "EOMONTH", anaplan: "END + ADDMONTHS", type: "alternative", category: "Date & Time", notes: "Combine ADDMONTHS to shift the date, then use END() or DAYSINMONTH to find the month's last day." },
  { excel: "WEEKDAY", anaplan: "WEEKDAY", type: "direct", category: "Date & Time", notes: "Direct equivalent. Returns 1–7 representing the day of the week." },
  { excel: "YEARFRAC", anaplan: "YEARFRAC", type: "direct", category: "Date & Time", notes: "Direct equivalent. Returns the fraction of a year between two dates." },
  { excel: "NETWORKDAYS", anaplan: "Custom formula", type: "none", category: "Date & Time", notes: "No direct equivalent. Build using DAYS() minus weekend count, or use WEEKDAY() to exclude weekends in a daily model." },
  { excel: "DATEDIF", anaplan: "Date arithmetic", type: "alternative", category: "Date & Time", notes: "Use direct date subtraction (Date2 - Date1) for day differences, or MONTH/YEAR functions for month/year differences." },

  // ── Statistical / Aggregation ──
  { excel: "AVERAGE", anaplan: "AVERAGE", type: "alternative", category: "Statistical", notes: "Anaplan AVERAGE is an aggregation function using mappings. For averaging two values: (A + B) / 2." },
  { excel: "AVERAGEIF", anaplan: "AVERAGE + mapping", type: "alternative", category: "Statistical", notes: "Use AVERAGE aggregation with a mapping that filters to the desired subset." },
  { excel: "COUNT", anaplan: "SUM + Boolean", type: "alternative", category: "Statistical", notes: "No direct COUNT. Use SUM on a Boolean line item (ISNOTBLANK(Value)) to count non-blank entries." },
  { excel: "COUNTA", anaplan: "SUM + ISNOTBLANK", type: "alternative", category: "Statistical", notes: "Count non-blank cells: create a Boolean ISNOTBLANK(Value), then SUM it across the list dimension." },
  { excel: "COUNTIF", anaplan: "SUM + Boolean", type: "alternative", category: "Statistical", notes: "Create a Boolean line item for the condition, then SUM it. E.g., to count revenue > 1000: SUM(Revenue > 1000)." },
  { excel: "MAX", anaplan: "MAX", type: "direct", category: "Statistical", notes: "Direct equivalent for comparing values: MAX(A, B). Also available as an aggregation function across lists." },
  { excel: "MIN", anaplan: "MIN", type: "direct", category: "Statistical", notes: "Direct equivalent for comparing values: MIN(A, B). Also available as an aggregation function across lists." },
  { excel: "RANK", anaplan: "RANK", type: "direct", category: "Statistical", notes: "Direct equivalent. Assigns sequential rankings starting at 1." },
  { excel: "LARGE", anaplan: "RANK + SELECT", type: "alternative", category: "Statistical", notes: "No direct LARGE. Use RANK to order values, then use conditional logic to retrieve the Nth largest." },
  { excel: "SMALL", anaplan: "RANK + SELECT", type: "alternative", category: "Statistical", notes: "No direct SMALL. Use RANK (ascending) to order values, then retrieve the Nth smallest." },

  // ── Financial ──
  { excel: "CUMIPMT", anaplan: "CUMIPMT", type: "direct", category: "Financial", notes: "Direct equivalent. Calculates cumulative interest paid over a period." },
  { excel: "CUMPRINC", anaplan: "CUMPRINC", type: "direct", category: "Financial", notes: "Direct equivalent. Calculates cumulative principal paid over a period." },
  { excel: "DURATION", anaplan: "DURATION", type: "direct", category: "Financial", notes: "Direct equivalent. Calculates the Macauley duration of a bond." },
  { excel: "FV", anaplan: "FV", type: "direct", category: "Financial", notes: "Direct equivalent. Calculates the future value of an investment." },
  { excel: "IPMT", anaplan: "IPMT", type: "direct", category: "Financial", notes: "Direct equivalent. Returns the interest portion of a payment." },
  { excel: "IRR", anaplan: "IRR", type: "direct", category: "Financial", notes: "Direct equivalent. Calculates the internal rate of return for a series of cash flows." },
  { excel: "MDURATION", anaplan: "MDURATION", type: "direct", category: "Financial", notes: "Direct equivalent. Calculates modified duration." },
  { excel: "NPER", anaplan: "NPER", type: "direct", category: "Financial", notes: "Direct equivalent. Returns the number of periods for an investment." },
  { excel: "NPV", anaplan: "NPV", type: "direct", category: "Financial", notes: "Direct equivalent. Calculates net present value." },
  { excel: "PMT", anaplan: "PMT", type: "direct", category: "Financial", notes: "Direct equivalent. Calculates the periodic payment for a loan." },
  { excel: "PPMT", anaplan: "PPMT", type: "direct", category: "Financial", notes: "Direct equivalent. Returns the principal portion of a payment." },
  { excel: "PRICE", anaplan: "PRICE", type: "direct", category: "Financial", notes: "Direct equivalent. Calculates bond price per 100 face value." },
  { excel: "PV", anaplan: "PV", type: "direct", category: "Financial", notes: "Direct equivalent. Calculates the present value of an investment." },
  { excel: "RATE", anaplan: "RATE", type: "direct", category: "Financial", notes: "Direct equivalent. Calculates the interest rate per period." },
  { excel: "YIELD", anaplan: "YIELD", type: "direct", category: "Financial", notes: "Direct equivalent. Calculates bond yield to maturity." },
  { excel: "COUPDAYBS", anaplan: "COUPDAYBS", type: "direct", category: "Financial", notes: "Direct equivalent. Days from coupon period start to settlement." },
  { excel: "COUPDAYS", anaplan: "COUPDAYS", type: "direct", category: "Financial", notes: "Direct equivalent. Number of days in the coupon period." },
  { excel: "COUPDAYSNC", anaplan: "COUPDAYSNC", type: "direct", category: "Financial", notes: "Direct equivalent. Days from settlement to next coupon." },
  { excel: "COUPNCD", anaplan: "COUPNCD", type: "direct", category: "Financial", notes: "Direct equivalent. Next coupon date after settlement." },
  { excel: "COUPNUM", anaplan: "COUPNUM", type: "direct", category: "Financial", notes: "Direct equivalent. Number of remaining coupon payments." },
  { excel: "COUPPCD", anaplan: "COUPPCD", type: "direct", category: "Financial", notes: "Direct equivalent. Previous coupon date before settlement." },

  // ── No Equivalent ──
  { excel: "INDIRECT", anaplan: "No equivalent", type: "none", category: "Lookup & Reference", notes: "No equivalent. Anaplan does not support dynamic cell references. Use LOOKUP with mapping line items instead." },
  { excel: "TRANSPOSE", anaplan: "No equivalent", type: "none", category: "Lookup & Reference", notes: "No equivalent. Anaplan's multi-dimensional modules handle row/column orientation differently through views." },
  { excel: "CELL", anaplan: "No equivalent", type: "none", category: "Information", notes: "No equivalent. Anaplan does not expose cell-level metadata." },
  { excel: "CHAR", anaplan: "No equivalent", type: "none", category: "Text", notes: "No equivalent. Anaplan has no character code functions." },
  { excel: "CLEAN", anaplan: "TRIM", type: "alternative", category: "Text", notes: "TRIM removes extra spaces. For non-printable characters, use SUBSTITUTE to remove specific characters." },
  { excel: "CODE", anaplan: "CODE (different)", type: "alternative", category: "Text", notes: "Excel CODE returns ASCII value. Anaplan CODE returns a list item's code property—completely different functionality." },
  { excel: "SUMIFS", anaplan: "SUM + mapping + Boolean", type: "alternative", category: "Math & Trig", notes: "Create Boolean line items for each condition, combine with AND, then use SUM aggregation with mappings." },
  { excel: "COUNTIFS", anaplan: "SUM + Boolean", type: "alternative", category: "Statistical", notes: "Create a combined Boolean condition, then SUM across the list to count matching items." },
  { excel: "XLOOKUP", anaplan: "LOOKUP", type: "alternative", category: "Lookup & Reference", notes: "Anaplan LOOKUP with mapping line items replaces XLOOKUP. Define a mapping that links source to target dimensions." },
  { excel: "SWITCH", anaplan: "Nested IF THEN ELSE", type: "alternative", category: "Logical", notes: "Use nested IF THEN ELSE statements: IF x = 1 THEN \"A\" ELSE IF x = 2 THEN \"B\" ELSE \"C\"." },
  { excel: "IFS", anaplan: "Nested IF THEN ELSE", type: "alternative", category: "Logical", notes: "Same as SWITCH—use nested IF THEN ELSE for multiple condition checks." },
  { excel: "SORT", anaplan: "RANK", type: "alternative", category: "Lookup & Reference", notes: "Use RANK to assign ordinal positions. Anaplan views can be sorted by line item values." },
  { excel: "UNIQUE", anaplan: "ISFIRSTOCCURRENCE", type: "alternative", category: "Lookup & Reference", notes: "ISFIRSTOCCURRENCE flags the first occurrence of each value. Filter on TRUE to get unique entries." },
  { excel: "XIRR", anaplan: "IRR (with dates)", type: "alternative", category: "Financial", notes: "Anaplan IRR supports an irregular cash flow variant: IRR(Cash flows, Dates, List)." }
];
